name: liquid_avatar
description:  Liquid Avatar Application using Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  camera:
  path_provider:
  path:
  ff_navigation_bar: ^0.0.1
  http: 0.12.1

  barcode_scan: ^3.0.1

dev_dependencies:
  flutter_launcher_icons: 0.7.5
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/kabn-icon.png"


flutter:
  uses-material-design: true
  assets:
    - images/
    - images/avatar/male/alien/
    - images/avatar/male/common/
    - images/avatar/male/robot/
    - images/avatar/male/vampire/
    - images/avatar/male/zombie/
    - images/avatar/female/afro/
    - images/avatar/female/alien/
    - images/avatar/female/common/
    - images/avatar/female/robot/
    - images/avatar/female/vampire/
    - images/avatar/female/zombie/
    - images/icons/
  fonts:
    - family: Montserrat
      fonts:
# Maybe even more fonts/families will be added in the future
        - asset: fonts/Montserrat-Regular.ttf